[project]
name = "libdraw"
version = "0.0.1"
description = "Just draw stuff"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "ultraplot>=1.60.2",
]

[tool.setuptools]
py-modules = ["Draw", "Data"]
